-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 19:06:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HilfeDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HilfeDb` ;

-- -----------------------------------------------------
-- Schema HilfeDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HilfeDb` DEFAULT CHARACTER SET utf8 ;
USE `HilfeDb` ;

-- -----------------------------------------------------
-- Table `HilfeDb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HilfeDb`.`User` ;

CREATE TABLE IF NOT EXISTS `HilfeDb`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Salt` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Bio` VARCHAR(45) NULL,
  `Birthday` VARCHAR(45) NULL,
  `PubKey` VARCHAR(45) NULL,
  `FotoProfilo` VARCHAR(100) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HilfeDb`.`PostInterventi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HilfeDb`.`PostInterventi` ;

CREATE TABLE IF NOT EXISTS `HilfeDb`.`PostInterventi` (
  `idPostIntervento` INT NOT NULL,
  `TitoloPost` VARCHAR(100) NULL,
  `DescrizionePost` VARCHAR(500) NULL,
  `DataIntervento` DATETIME NULL,
  `DataPubblicazione` DATETIME NULL,
  `PersoreRichieste` INT UNSIGNED NULL,
  `PosizioneLongitudine` DECIMAL(6) NULL,
  `PosizioneLatitudine` DECIMAL(6) NULL,
  PRIMARY KEY (`idPostIntervento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HilfeDb`.`Interventi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HilfeDb`.`Interventi` ;

CREATE TABLE IF NOT EXISTS `HilfeDb`.`Interventi` (
  `idPostInterventi` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idPostInterventi`, `idUser`),
  INDEX `fk_Interventi_PostInterventi1_idx` (`idPostInterventi` ASC) ,
  INDEX `fk_Interventi_User1_idx` (`idUser` ASC) ,
  CONSTRAINT `fk_Interventi_PostInterventi1`
    FOREIGN KEY (`idPostInterventi`)
    REFERENCES `HilfeDb`.`PostInterventi` (`idPostIntervento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interventi_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `HilfeDb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HilfeDb`.`Materiale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HilfeDb`.`Materiale` ;

CREATE TABLE IF NOT EXISTS `HilfeDb`.`Materiale` (
  `idMateriale` INT NOT NULL,
  `idPostInterventi` INT NULL,
  `DescrizioneMateriale` VARCHAR(200) NULL,
  `Unita` INT UNSIGNED NULL,
  `idPostIntervento` INT NOT NULL,
  PRIMARY KEY (`idMateriale`),
  INDEX `fk_Materiale_PostInterventi1_idx` (`idPostIntervento` ASC) ,
  CONSTRAINT `fk_Materiale_PostInterventi1`
    FOREIGN KEY (`idPostIntervento`)
    REFERENCES `HilfeDb`.`PostInterventi` (`idPostIntervento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HilfeDb`.`FornitoriMateriali`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HilfeDb`.`FornitoriMateriali` ;

CREATE TABLE IF NOT EXISTS `HilfeDb`.`FornitoriMateriali` (
  `idMateriale` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idMateriale`, `idUser`),
  INDEX `fk_FornitoriMateriali_User1_idx` (`idUser` ASC) ,
  CONSTRAINT `fk_FornitoriMateriali_Materiale1`
    FOREIGN KEY (`idMateriale`)
    REFERENCES `HilfeDb`.`Materiale` (`idMateriale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FornitoriMateriali_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `HilfeDb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HilfeDb`.`PostComunicazioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HilfeDb`.`PostComunicazioni` ;

CREATE TABLE IF NOT EXISTS `HilfeDb`.`PostComunicazioni` (
  `idPostComunicazione` INT NOT NULL,
  `idUser` INT NOT NULL,
  `TitoloPost` VARCHAR(100) NULL,
  `DescrizionePost` VARCHAR(500) NULL,
  `Foto` VARCHAR(100) NULL,
  PRIMARY KEY (`idPostComunicazione`),
  CONSTRAINT `fk_PostComunicazioni_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `HilfeDb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HilfeDb`.`Seguiti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HilfeDb`.`Seguiti` ;

CREATE TABLE IF NOT EXISTS `HilfeDb`.`Seguiti` (
  `idSeguace` INT NOT NULL,
  `idSeguito` INT NOT NULL,
  PRIMARY KEY (`idSeguace`, `idSeguito`),
  INDEX `fk_Seguiti_User2_idx` (`idSeguito` ASC) ,
  CONSTRAINT `fk_Seguiti_User1`
    FOREIGN KEY (`idSeguace`)
    REFERENCES `HilfeDb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguiti_User2`
    FOREIGN KEY (`idSeguito`)
    REFERENCES `HilfeDb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
